//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Itinerario_Curso = new HashSet<Itinerario_Curso>();
            this.Ruta_Adm = new HashSet<Ruta_Adm>();
        }
    
        public int idcurso { get; set; }
        public Nullable<int> curso_idprofesor { get; set; }
        public Nullable<int> curso_idescuela { get; set; }
        public string curso_nivel { get; set; }
        public string curso_nombre { get; set; }
        public string curso_logo { get; set; }
    
        public virtual Escuela Escuela { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerario_Curso> Itinerario_Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruta_Adm> Ruta_Adm { get; set; }
    }
}
