//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interes
    {
        public int idinteres { get; set; }
        public Nullable<int> idalumno { get; set; }
        public string interes_nombre { get; set; }
        public string interes_descripcion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
