//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario_Aprendizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerario_Aprendizaje()
        {
            this.Itinerario_Curso = new HashSet<Itinerario_Curso>();
        }
    
        public int iditinerario { get; set; }
        public Nullable<int> iditi_alumno { get; set; }
        public Nullable<int> iditi_inscrip { get; set; }
        public string iti_nombre { get; set; }
        public Nullable<System.DateTime> iti_fech_creacion { get; set; }
        public string estado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerario_Curso> Itinerario_Curso { get; set; }
    }
}
