//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario_Curso
    {
        public int id_iti_curso { get; set; }
        public Nullable<int> id_iticurso_idcurso { get; set; }
        public Nullable<int> id_iticurso_iti { get; set; }
        public string iti_nombre { get; set; }
        public Nullable<System.DateTime> iti_fech_inicio { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Itinerario_Aprendizaje Itinerario_Aprendizaje { get; set; }
    }
}
