//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlatziEntities2 : DbContext
    {
        public PlatziEntities2()
            : base("name=PlatziEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Alumno_Empleo> Alumno_Empleo { get; set; }
        public virtual DbSet<Categoria_Empleo> Categoria_Empleo { get; set; }
        public virtual DbSet<Categoria_Escuela> Categoria_Escuela { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Empleo> Empleo { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<Interes> Interes { get; set; }
        public virtual DbSet<Itinerario_Aprendizaje> Itinerario_Aprendizaje { get; set; }
        public virtual DbSet<Itinerario_Curso> Itinerario_Curso { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Pago_Tarjeta> Pago_Tarjeta { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Ruta_Adm> Ruta_Adm { get; set; }
        public virtual DbSet<Suscripcion> Suscripcion { get; set; }
        public virtual DbSet<Tipo_Pago> Tipo_Pago { get; set; }
    }
}
