//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public string correo_destino { get; set; }
        public string nombre_destino { get; set; }
        public string informacion_destino { get; set; }
        public Nullable<int> ipnotif { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idalumno { get; set; }
        public int idnotificacion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
