//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Pago_Tarjeta = new HashSet<Pago_Tarjeta>();
        }
    
        public int idpago { get; set; }
        public Nullable<int> idsuscripcion { get; set; }
        public Nullable<int> idplan { get; set; }
        public Nullable<int> tipo_pago { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Tarjeta> Pago_Tarjeta { get; set; }
        public virtual Planes Planes { get; set; }
        public virtual Suscripcion Suscripcion { get; set; }
    }
}
