//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int idprofesor { get; set; }
        public string prof_usunombre { get; set; }
        public string profcorreo { get; set; }
        public Nullable<int> pro_perfil { get; set; }
        public string profcontrasena { get; set; }
        public string prof_nombre { get; set; }
        public string prof_apellidos { get; set; }
        public string prof_documento { get; set; }
        public string prof_especialidad { get; set; }
        public string prof_telef { get; set; }
        public string prof_foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
