//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRegistro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta_Adm
    {
        public int idruta_adm { get; set; }
        public string ruta_adm_nombre { get; set; }
        public string ruta_adm_interes { get; set; }
        public string ruta_adm_tema { get; set; }
        public string ruta_adm_nivel { get; set; }
        public string ruta_adm_descripcion { get; set; }
        public Nullable<int> id_ruta_adm_curso { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
