//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int idalumno { get; set; }
        public string usu_nombre { get; set; }
        public string alu_correo { get; set; }
        public string alu_contrasena { get; set; }
        public string alu_nombres { get; set; }
        public string aluapellidos { get; set; }
        public Nullable<int> alutelefono { get; set; }
        public string resp_w { get; set; }
        public Nullable<int> compromiso_hr { get; set; }
        public string interes { get; set; }
        public string escuela { get; set; }
    }
}
